services:
  frontend:
    build:
      context: ./0.Frontend
    ports:
    - "3000:3000"
    environment:
      - ENV_VAR=VALUE
    env_file:
      - ./0.Frontend/.env 
    depends_on:
      - datacollector


  datacollector:
    build:
      context: ./1.DataCollector
    ports:
      - "5500:5500"
    environment:
      - ENV_VAR=VALUE
    env_file:
      - ./1.DataCollector/.env 
    depends_on:
      - promptgen

  promptgen:
    build:
      context: ./2.PromptGen
    ports:
      - "5600:5600"
    environment:
      - ENV_VAR=VALUE
    env_file:
      - ./2.PromptGen/.env 
    depends_on:

      - llmengine
      - resultaggregator

  llmengine:
    build:
      context: ./3.LLMEngine
    ports:
      - "5700:5700"
    environment:
      - ENV_VAR=VALUE
    env_file:
      - ./3.LLMEngine/.env 

  resultaggregator:
    build:
      context: ./4.ResultAggregator
    ports:
      - "5800:5800"
    environment:
      - ENV_VAR=VALUE
    env_file:
      - ./4.ResultAggregator/.env 

networks:
  default:
    driver: bridge
